### ISSUE TITLE
Default kong token access policy for tls certificate/key is wrong

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/security-secret-store#38]
The current hcl access for the generated kong token has this access for the certificate and private key that is used by `security-api-gateway` when loading the certificates into Kong:

https://github.com/edgexfoundry/security-secret-store/blob/c0ea61323ea8862d844201b788fa8bc52da881ea/core/res/vault-policy-kong.hcl#L6-L9

This is wrong, as this only allows accessing things underneath `secret/edgex/pki/tls/edgex-kong/*` i.e. something like 

```
curl localhost:8200/v1/secret/edgex/pki/tls/edgex-kong/something --header "X-Vault-Token: <some uuid>"
```

Which is not the request that security-api-gateway by default does. By default security-secret-store's `vault-worker` puts the certificate and private key at `/secret/edgex/pki/tls/edgex-kong`, and security-api-gateway's `edgexproxy` also expects to be able to access it there, so the access policy should really be:

```
# List/Read only for the TLS materials: private key and certificate
path "secret/edgex/pki/tls/edgex-kong" {
  capabilities = ["list", "read"]
}
```

CC @tingyuz as I mentioned this on Rocket.Chat earlier today. This should also be considered a blocker for Delhi I think.

**Comment by anonymouse64** [comment]
I can submit a PR for this as it's a really simple change

**Comment by alain2sf** [comment]
@anonymouse64 Sure, I can proceed as well, I found this typo last week when testing the kong token and the TTL token attribute. It was decided to wait for Delhi to be released and then push this fix in a later dot release, as kong service does not use the kong token and therefore the policies are not used.
We would have then pushed several other modifications in order to use the service tokens and not the root token anymore. There are also some Vault configuration tweaks to apply in order to handle the token TTLs. Let me know.
